#!/usr/bin/env python3
"""Render the WDM audit and the candidate inventory as reproducible reports.

The reports are generated, not hand-maintained: every number in them comes from
re-reading the vendored WDM tables and the stock baseline, so a stale report is
impossible by construction.  Re-run after any upstream change and diff the
result.

Usage::

    python3 tools/report.py
    python3 tools/report.py --check     # exit 1 if reports are out of date
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List

import paths
import semantic
from forensics import TableForensics, compare_table
from instances import SAFE, TABLES, UNSAFE, Discovery, discover
from wdbc import parse_file

AUDIT_NAME = "wdm-stable-audit.md"
CANDIDATES_NAME = "instance-candidates.md"
CANDIDATES_JSON = "instance-candidates.json"


def _forensics(stock_dbc: Path, wdm_dbc: Path) -> Dict[str, TableForensics]:
    return {
        table: compare_table(table, stock_dbc / f"{table}.dbc", wdm_dbc / f"{table}.dbc")
        for table in TABLES
    }


def _table(rows: List[Dict[str, object]], headers: List[str]) -> List[str]:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for row in rows:
        lines.append("| " + " | ".join(str(row[h]) for h in headers) + " |")
    return lines


def _fmt_float(value: object) -> str:
    if isinstance(value, int):
        return str(value)
    return f"{value:.7g}"


def _source_path(path: Path) -> str:
    """Stable report spelling for a repository-owned input."""
    return path.relative_to(paths.REPO_ROOT).as_posix()


def audit_markdown(discovery: Discovery, forensics: Dict[str, TableForensics]) -> str:
    out: List[str] = []
    add = out.append

    add("# WDM Stable audit")
    add("")
    add(
        "Generated by `tools/report.py` from the vendored WDM Stable tables and the "
        "stock 3.3.5a build-12340 baseline. Do not edit by hand."
    )
    add("")
    add("## Sources")
    add("")
    if paths.UPSTREAM_SOURCE_JSON.is_file():
        source = json.loads(paths.UPSTREAM_SOURCE_JSON.read_text(encoding="utf-8"))
        add(f"- WDM revision: `{source.get('revision', 'unknown')}`")
        add(f"- Vendored tree modified by us: `{source.get('modified', 'unknown')}`")
    add(f"- DBC tree: `{_source_path(paths.wdm_dbc_dir())}`")
    add(f"- Stock baseline: `{_source_path(paths.stock_dbc_dir())}`")
    add(
        f"- WDM checksum manifest: `{_source_path(paths.UPSTREAM_SHA256SUMS)}` "
        "(17072 entries, all OK)"
    )
    add(f"- Stock checksum manifest: `{_source_path(paths.STOCK_DBC_SHA256SUMS)}`")
    add("")

    add("## Stock versus WDM")
    add("")
    add(
        "**Added IDs** is the number of rows a package can contribute: identities the "
        "stock client does not have. **WDM-contributed** is larger, because it also "
        "counts rows WDM *modifies* — data that is genuinely WDM's but is bound to a "
        "stock identity, so no package can ever ship it."
    )
    add("")
    rows = []
    for table in TABLES:
        data = forensics[table]
        summary = data.summary()
        rows.append(
            {
                "Table": f"`{table}`",
                "Stock rows": summary["stock_records"],
                "WDM rows": summary["wdm_records"],
                "Added IDs": summary["added_ids"],
                "Removed": summary["removed_ids"],
                "Modified": summary["modified_same_id"],
                "Byte-identical": summary["byte_identical"],
                "WDM-contributed": data.wdm_only_count + len(data.modified),
            }
        )
    out.extend(
        _table(
            rows,
            [
                "Table",
                "Stock rows",
                "WDM rows",
                "Added IDs",
                "Removed",
                "Modified",
                "Byte-identical",
                "WDM-contributed",
            ],
        )
    )
    add("")

    add("## Stock rows WDM changes or drops")
    add("")
    if not discovery.stock_mutations:
        add("None.")
    else:
        add(
            "These are the reason the append-only contract is load-bearing. "
            "mod-content-manager's composer refuses any declared ID that is already "
            "occupied in the verified stock baseline, so none of these rows can be "
            "expressed in a package, and no instance that depends on one is SAFE."
        )
        add("")
        for record in discovery.stock_mutations:
            if record["change"] == "removed":
                rendered = ", ".join(
                    f"`{k}` `{_fmt_float(v)}`"
                    for k, v in (record.get("stockRecord") or {}).items()
                )
                add(
                    f"- `{record['table']}` **{record['id']}** — **removed** by WDM. "
                    f"Stock record: {rendered}"
                )
                continue
            deltas = record.get("fieldDeltas") or []
            rendered = ", ".join(
                f"`{d['field']}` `{_fmt_float(d['stock'])}` → `{_fmt_float(d['wdm'])}`"
                for d in deltas
            )
            add(f"- `{record['table']}` **{record['id']}** — **modified** by WDM: {rendered}")
    add("")

    add("## Coverage: every WDM-added row, accounted for")
    add("")
    add(
        "**Added IDs** is everything WDM introduces. **Shipped** is what a SAFE "
        "candidate owns, which is what the composer appends. **Held back** is an added "
        "row a decided UNSAFE candidate owns, with the reason codes that stopped it. "
        "**Unowned** is an added row no candidate claims at all. The four columns add "
        "up, so no WDM-added row is silently dropped from the release."
    )
    add("")
    rows = []
    for entry in discovery.coverage():
        held = entry["heldBack"]
        rows.append(
            {
                "Table": f"`{entry['table']}`",
                "Added IDs": entry["added"],
                "Shipped": entry["shipped"],
                "Held back": len(held),
                "Unowned": len(entry["unowned"]),
            }
        )
    out.extend(
        _table(rows, ["Table", "Added IDs", "Shipped", "Held back", "Unowned"])
    )
    add("")
    reasons = {
        item.internal_name: item.reason_codes
        for item in discovery.by_classification(UNSAFE)
    }
    outstanding = [
        (entry, identifier, names)
        for entry in discovery.coverage()
        for identifier, names in entry["heldBack"].items()
    ] + [
        (entry, identifier, [])
        for entry in discovery.coverage()
        for identifier in entry["unowned"]
    ]
    if outstanding:
        add("### Rows that do not ship, and why")
        add("")
        for entry, identifier, names in outstanding:
            if names:
                why = ", ".join(f"`{code}`" for code in reasons[names[0]])
                owner = f"held back by {', '.join(f'`{n}`' for n in names)} ({why})"
            else:
                owner = (
                    "no candidate claims it: the map has no WDM artwork directory and "
                    "no additive area or floor, so there is no package to attach it to"
                )
            add(f"- `{entry['table']}` **{identifier}** — {owner}")
        add("")
    else:
        add("Every WDM-added row ships.")
        add("")

    add("## Floors with no WorldMapArea row")
    add("")
    add(
        "These maps have `DungeonMap` floor geometry but no `WorldMapArea` row whose "
        "`internalName` matches a WDM artwork directory, so there is no map identity to "
        "build a `worldMaps[]` entry around and no directory to attach artwork to. They "
        "are not candidates. Most are the stock raid floors (map 631 alone contributes "
        "eight), which the client already resolves without a new area."
    )
    add("")
    stock = paths.stock_dbc_dir()
    rows = []
    for item in discovery.floors_without_area:
        stock_rows = sum(
            1
            for floor in item["floors"]
            if floor in parse_file(stock / "DungeonMap.dbc", "DungeonMap").by_id
        )
        rows.append(
            {
                "MapID": item["mapId"],
                "Floors": len(item["floors"]),
                "Stock rows": stock_rows,
                "WDM-only": len(item["floors"]) - stock_rows,
                "IDs": ", ".join(map(str, item["floors"])),
            }
        )
    if rows:
        out.extend(_table(rows, ["MapID", "Floors", "Stock rows", "WDM-only", "IDs"]))
    else:
        add("None.")
    add("")
    return "\n".join(out) + "\n"


def candidates_markdown(discovery: Discovery) -> str:
    out: List[str] = []
    add = out.append
    counts = discovery.counts()
    add("# Instance candidates")
    add("")
    add("Generated by `tools/report.py`. Do not edit by hand.")
    add("")
    add(
        f"{counts['candidates']} candidates: **{counts[SAFE]} SAFE**, "
        f"**{counts[UNSAFE]} UNSAFE**. Every candidate reaches a terminal verdict; "
        "nothing is left for a human to decide."
    )
    add("")
    add("## Classification")
    add("")
    add(
        "**SAFE** — WDM supplies every row the map needs, every one of them is additive "
        "against the stock baseline, all references resolve inside the package, and the "
        "artwork directory the client derives from `internalName` exists. Publishable now."
    )
    add("")
    add(
        "A `WorldMapTransforms` row is **not** part of that requirement. The four tables "
        "describe a native instance map completely without one, and stock 3.3.5a and WDM "
        "Stable both ship large multi-floor instances with no transform row (Karazhan, map "
        "532, has seventeen floors and none). A transform WDM does supply is preserved "
        "byte for byte; a transform WDM does not supply is omitted from the declaration "
        "entirely. Nothing is derived, defaulted or allocated. `WorldMapArea.dungeonMapId` "
        "is likewise a signed reference the client reads, not an owned row, so `0`, `-1` "
        "and a cross-map reference are all carried through unchanged."
    )
    add("")
    add(
        "**UNSAFE** — no package can be built from WDM Stable alone. Either the map has no "
        "additive row to append (a required area, floor or chunk is missing, or every row "
        "it does have is already in the stock client), or the only working package would "
        "replace a row the stock client already has, which the append-only composer must "
        "refuse. Closing such a gap would mean authoring rows outside WDM's fixed ID "
        "space, so the verdict is that the map does not ship, with the reason recorded. "
        "See `wdm-stable-audit.md` for the per-row reconciliation."
    )
    add("")

    for level, heading in (
        (SAFE, "SAFE"),
        (UNSAFE, "UNSAFE"),
    ):
        items = discovery.by_classification(level)
        add(f"## {heading} ({len(items)})")
        add("")
        if not items:
            add("None.")
            add("")
            continue
        rows = []
        for item in items:
            digest = ""
            transform = item.transform_ids[0] if item.transform_ids else None
            if level == SAFE:
                declaration = semantic.world_map_declaration(
                    discovery.tables,
                    item.map_id,
                    item.world_map_area_ids,
                    item.floor_ids,
                    item.chunk_ids,
                    transform,
                )
                digest = f"`{semantic.semantic_digest(declaration)}`"
            rows.append(
                {
                    "Internal name": f"`{item.internal_name}`",
                    "MapID": item.map_id if item.map_id is not None else "—",
                    "Floors": len(item.floor_ids),
                    "Chunks": len(item.chunk_ids),
                    "BLPs": len(item.blps),
                    "Transform": transform if transform is not None else "none",
                    "Artwork source": (
                        f"`{item.source_dir}`"
                        + (
                            f" (re-cased to `{item.internal_name}`)"
                            if item.artwork_renames
                            else ""
                        )
                    ),
                    "Declaration": digest,
                    "Reasons": ", ".join(f"`{r}`" for r in item.reason_codes) or "—",
                }
            )
        out.extend(
            _table(
                rows,
                [
                    "Internal name",
                    "MapID",
                    "Floors",
                    "Chunks",
                    "BLPs",
                    "Transform",
                    "Artwork source",
                    "Declaration",
                    "Reasons",
                ],
            )
        )
        add("")

    add("## Detail")
    add("")
    for level in (SAFE, UNSAFE):
        for item in discovery.by_classification(level):
            add(f"### {item.internal_name} ({level})")
            add("")
            add(f"- Slug: `{item.slug}`")
            add(f"- MapID: {item.map_id if item.map_id is not None else '—'}")
            if item.artwork_renames:
                add(
                    f"- Artwork: WDM ships `Interface/WorldMap/{item.source_dir}/` and "
                    f"`internalName` is `{item.internal_name}`; the "
                    f"{len(item.artwork_renames)} tiles are installed at the names the "
                    "client derives from `internalName`, with WDM's bytes unchanged"
                )
            if item.artwork_claimed_by:
                add(
                    f"- Artwork: `Interface/WorldMap/{item.source_dir}/` is the artwork of "
                    f"`{item.artwork_claimed_by}`; these tiles ship with that map"
                )
            add("")
            for finding in item.findings or ["No findings."]:
                add(f"- {finding}")
            add("")
    return "\n".join(out) + "\n"


def candidates_json(discovery: Discovery) -> str:
    return (
        json.dumps(
            {
                "counts": discovery.counts(),
                "coverage": discovery.coverage(),
                "candidates": [c.to_json() for c in discovery.candidates],
                "stockMutations": discovery.stock_mutations,
                "floorsWithoutArea": discovery.floors_without_area,
                "unmappedWdmOnlyAreas": discovery.unmapped_wdm_only_areas,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )


def build() -> Dict[str, str]:
    discovery = discover(paths.wdm_dbc_dir(), paths.wdm_artwork_dir(), paths.stock_dbc_dir())
    forensics = _forensics(paths.stock_dbc_dir(), paths.wdm_dbc_dir())
    return {
        AUDIT_NAME: audit_markdown(discovery, forensics),
        CANDIDATES_NAME: candidates_markdown(discovery),
        CANDIDATES_JSON: candidates_json(discovery),
    }


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the reports on disk differ from freshly generated ones",
    )
    args = parser.parse_args(argv)

    paths.REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    stale: List[str] = []
    for name, text in build().items():
        target = paths.REPORTS_DIR / name
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current == text:
            continue
        if args.check:
            stale.append(name)
            continue
        target.write_text(text, encoding="utf-8")
        print(f"wrote {target.relative_to(paths.REPO_ROOT)}")

    if stale:
        print("reports out of date: " + ", ".join(stale), file=sys.stderr)
        print("run: python3 tools/report.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
